kind: pipeline
type: docker
name: ci/cd
clone:
  disable: true
steps:
  - name: clone
    image: bitnami/git
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - mkdir -p $HOME/.ssh/
      - echo -n "$SSH_KEY" > $HOME/.ssh/id_ed25519
      - chmod 600 $HOME/.ssh/id_ed25519

      - touch $HOME/.ssh/known_hosts
      - chmod 600 $HOME/.ssh/known_hosts
      - touch $HOME/.ssh/config
      - chmod 600 $HOME/.ssh/config
      - echo "Host github.com\n    Hostname ssh.github.com\n    Port 443\n    User git" > $HOME/.ssh/config
      - echo "[ssh.github.com]:443 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" >> $HOME/.ssh/known_hosts
      - git config --global init.defaultBranch main
      - git init
      - git config advice.detachedHead false
      - git remote add origin $DRONE_GIT_SSH_URL
      - git fetch --no-tags --prune --no-recurse-submodules origin $DRONE_COMMIT_BRANCH
      - git checkout $DRONE_COMMIT
  - name: build
    image: node:lts-alpine
    environment:
      PROM_URL:
        from_secret: PROM_URL
    depends_on:
      - clone
    commands:
      - corepack enable
      - corepack prepare pnpm@latest-8 --activate
      - pnpm -v
      - pnpm install
      - pnpm run build
      - pnpm prune --prod
  - name: build_docker
    image: plugins/docker
    depends_on:
      - build
    pull: if-not-exists
    settings:
      registry: hub.ccw.es
      username:
        from_secret: nexus_docker_username
      password:
        from_secret: nexus_docker_password
      repo: hub.ccw.es/home/blog
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
  - name: ssh
    image: appleboy/drone-ssh
    depends_on:
      - build_docker
    settings:
      host:
        from_secret: k8s_host
      username:
        from_secret: k8s_username
      key:
        from_secret: k8s_key
      port: 22
      command_timeout: 2m
      script:
        - kubectl apply -f https://git.ccw.es/ccw/yaml/raw/branch/master/monitor-status.yaml
        - kubectl set image deployment/monitor-status monitor-status=hub.ccw.es/home/monitor-status:${DRONE_COMMIT_SHA:0:8}
